# Docker-compose para poder probar el servicio de manera local.
services:

  launch:
    build: .
    ports:
      - 80:80
    networks:
      mynetwork:
        ipv4_address: 150.0.0.2

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 150.0.0.0/16