name: Pipeline

on:

  push:
    branches: [main]
    paths:
      - "index.html"

  pull_request:
    branches: [main]
    paths:
      - "index.html"

jobs:

  build_upload:
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test estatico
        run: echo "Aqui puedo hacer algunos test de código estatico"

      - name: Building
        run: docker build -t my_nginx .

      - name: Test de aceptacion
        run: |
          docker network create --subnet=150.0.0.0/16 my_net
          docker run --name my_run --network my_net --ip 150.0.0.2 -d my_nginx
          docker run --name my_test_machine --network my_net --ip 150.0.0.3 -d alpine:3.18 tail -f /dev/null
          docker ps
          docker exec my_test_machine apk add curl
          docker exec my_test_machine curl 150.0.0.2 -s
          docker stop my_test_machine
          docker rm my_test_machine
          docker stop my_run
          docker rm my_run
          docker network rm my_net

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Upload imagen
        run: |
          docker tag my_nginx luchopeschiutta/my_nginx:${{github.sha}}
          docker push luchopeschiutta/my_nginx:${{github.sha}}

  deploy:
    runs-on: ubuntu-20.04
    needs: build_upload
    if: ${{ success() }}

    steps:

      - name: Despliegue
        run: echo "Aqui escribo la secuencia de comandos para que alguna plataforma descargue la imagen y la despiegue"
    
