name: Pipeline

on:

  

  push:
    branches: [main]
    paths:
      - "index.html"

  pull_request:
    branches: [main]
    paths:
      - "index.html"

jobs:

  test_build_deploy:
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test estatico
        run: echo "Aqui puedo hacer algunos test de código estatico"

      - name: Building
        run: docker build -t my_nginx .

      - name: Test de aceptacion
        run: |
          docker network create my_net
          docker run --name my_run --expose 80 --network my_net --ip 10.0.0.2 -d my_nginx
          curl 10.0.0.2
          docker stop my-run
          docker rm my-run
          docker network rm my_net

      - name: Carga de la imagen a un registro
        run: echo "Aqui escribo la secuencia de comandos para cargar mi imagen en DockerHub, ECR u otros" # Pushear a DockerHub

      - name: Despliegue
        run: echo "Aqui escribo la secuencia de comandos para que alguna plataforma descargue la imagen y la despiegue" # Separar en un job aparte


    
