name: Pipeline

on:

  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:

  test_build_deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Clonacion
        run: git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"

      - name: Test estatico
        run: echo "Aqui puedo hacer algunos test de código estatico"

      - name: Building
        run: |
          pwd
          ls
          cd ./"$GITHUB_WORKDIR"
          pwd
          ls
          cd ./"$GITHUB_WORKDIR"
          pwd
          ls
          docker build -t my_nginx .

      - name: Test de aceptacion
        run: echo "Aqui puedo lanzar el servicio localmente y realizar algunos tests de aceptacion"

      - name: Carga de la imagen a un registro
        run: echo "Aqui escribo la secuencia de comandos para cargar mi imagen en DockerHub, ECR u otros"

      - name: Despliegue
        run: echo "Aqui escribo la secuencia de comandos para que alguna plataforma descargue la imagen y la despiegue"


    
